// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: echelon/vrf/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetRandomvalRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetRandomvalRequest) Reset()         { *m = QueryGetRandomvalRequest{} }
func (m *QueryGetRandomvalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRandomvalRequest) ProtoMessage()    {}
func (*QueryGetRandomvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{0}
}
func (m *QueryGetRandomvalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRandomvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRandomvalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRandomvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRandomvalRequest.Merge(m, src)
}
func (m *QueryGetRandomvalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRandomvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRandomvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRandomvalRequest proto.InternalMessageInfo

func (m *QueryGetRandomvalRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetRandomvalResponse struct {
	Randomval Randomval `protobuf:"bytes,1,opt,name=randomval,proto3" json:"randomval"`
}

func (m *QueryGetRandomvalResponse) Reset()         { *m = QueryGetRandomvalResponse{} }
func (m *QueryGetRandomvalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRandomvalResponse) ProtoMessage()    {}
func (*QueryGetRandomvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{1}
}
func (m *QueryGetRandomvalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRandomvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRandomvalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRandomvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRandomvalResponse.Merge(m, src)
}
func (m *QueryGetRandomvalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRandomvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRandomvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRandomvalResponse proto.InternalMessageInfo

func (m *QueryGetRandomvalResponse) GetRandomval() Randomval {
	if m != nil {
		return m.Randomval
	}
	return Randomval{}
}

type QueryAllRandomvalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRandomvalRequest) Reset()         { *m = QueryAllRandomvalRequest{} }
func (m *QueryAllRandomvalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRandomvalRequest) ProtoMessage()    {}
func (*QueryAllRandomvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{2}
}
func (m *QueryAllRandomvalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRandomvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRandomvalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRandomvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRandomvalRequest.Merge(m, src)
}
func (m *QueryAllRandomvalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRandomvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRandomvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRandomvalRequest proto.InternalMessageInfo

func (m *QueryAllRandomvalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRandomvalResponse struct {
	Randomval  []Randomval         `protobuf:"bytes,1,rep,name=randomval,proto3" json:"randomval"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRandomvalResponse) Reset()         { *m = QueryAllRandomvalResponse{} }
func (m *QueryAllRandomvalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRandomvalResponse) ProtoMessage()    {}
func (*QueryAllRandomvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{3}
}
func (m *QueryAllRandomvalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRandomvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRandomvalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRandomvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRandomvalResponse.Merge(m, src)
}
func (m *QueryAllRandomvalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRandomvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRandomvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRandomvalResponse proto.InternalMessageInfo

func (m *QueryAllRandomvalResponse) GetRandomval() []Randomval {
	if m != nil {
		return m.Randomval
	}
	return nil
}

func (m *QueryAllRandomvalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetUservalRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetUservalRequest) Reset()         { *m = QueryGetUservalRequest{} }
func (m *QueryGetUservalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUservalRequest) ProtoMessage()    {}
func (*QueryGetUservalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{4}
}
func (m *QueryGetUservalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUservalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUservalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUservalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUservalRequest.Merge(m, src)
}
func (m *QueryGetUservalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUservalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUservalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUservalRequest proto.InternalMessageInfo

func (m *QueryGetUservalRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetUservalResponse struct {
	Userval Userval `protobuf:"bytes,1,opt,name=userval,proto3" json:"userval"`
}

func (m *QueryGetUservalResponse) Reset()         { *m = QueryGetUservalResponse{} }
func (m *QueryGetUservalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUservalResponse) ProtoMessage()    {}
func (*QueryGetUservalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{5}
}
func (m *QueryGetUservalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUservalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUservalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUservalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUservalResponse.Merge(m, src)
}
func (m *QueryGetUservalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUservalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUservalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUservalResponse proto.InternalMessageInfo

func (m *QueryGetUservalResponse) GetUserval() Userval {
	if m != nil {
		return m.Userval
	}
	return Userval{}
}

type QueryAllUservalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUservalRequest) Reset()         { *m = QueryAllUservalRequest{} }
func (m *QueryAllUservalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllUservalRequest) ProtoMessage()    {}
func (*QueryAllUservalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{6}
}
func (m *QueryAllUservalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUservalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUservalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUservalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUservalRequest.Merge(m, src)
}
func (m *QueryAllUservalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUservalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUservalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUservalRequest proto.InternalMessageInfo

func (m *QueryAllUservalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllUservalResponse struct {
	Userval    []Userval           `protobuf:"bytes,1,rep,name=userval,proto3" json:"userval"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUservalResponse) Reset()         { *m = QueryAllUservalResponse{} }
func (m *QueryAllUservalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllUservalResponse) ProtoMessage()    {}
func (*QueryAllUservalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{7}
}
func (m *QueryAllUservalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUservalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUservalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUservalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUservalResponse.Merge(m, src)
}
func (m *QueryAllUservalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUservalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUservalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUservalResponse proto.InternalMessageInfo

func (m *QueryAllUservalResponse) GetUserval() []Userval {
	if m != nil {
		return m.Userval
	}
	return nil
}

func (m *QueryAllUservalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVerifyValuesRequest struct {
	Pubkey  string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Vrv     string `protobuf:"bytes,3,opt,name=vrv,proto3" json:"vrv,omitempty"`
	Proof   string `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *QueryVerifyValuesRequest) Reset()         { *m = QueryVerifyValuesRequest{} }
func (m *QueryVerifyValuesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyValuesRequest) ProtoMessage()    {}
func (*QueryVerifyValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{8}
}
func (m *QueryVerifyValuesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyValuesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyValuesRequest.Merge(m, src)
}
func (m *QueryVerifyValuesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyValuesRequest proto.InternalMessageInfo

func (m *QueryVerifyValuesRequest) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *QueryVerifyValuesRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryVerifyValuesRequest) GetVrv() string {
	if m != nil {
		return m.Vrv
	}
	return ""
}

func (m *QueryVerifyValuesRequest) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type QueryVerifyValuesResponse struct {
	Verified string `protobuf:"bytes,1,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (m *QueryVerifyValuesResponse) Reset()         { *m = QueryVerifyValuesResponse{} }
func (m *QueryVerifyValuesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyValuesResponse) ProtoMessage()    {}
func (*QueryVerifyValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c81a177218a0f596, []int{9}
}
func (m *QueryVerifyValuesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyValuesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyValuesResponse.Merge(m, src)
}
func (m *QueryVerifyValuesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyValuesResponse proto.InternalMessageInfo

func (m *QueryVerifyValuesResponse) GetVerified() string {
	if m != nil {
		return m.Verified
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryGetRandomvalRequest)(nil), "echelon.vrf.v1.QueryGetRandomvalRequest")
	proto.RegisterType((*QueryGetRandomvalResponse)(nil), "echelon.vrf.v1.QueryGetRandomvalResponse")
	proto.RegisterType((*QueryAllRandomvalRequest)(nil), "echelon.vrf.v1.QueryAllRandomvalRequest")
	proto.RegisterType((*QueryAllRandomvalResponse)(nil), "echelon.vrf.v1.QueryAllRandomvalResponse")
	proto.RegisterType((*QueryGetUservalRequest)(nil), "echelon.vrf.v1.QueryGetUservalRequest")
	proto.RegisterType((*QueryGetUservalResponse)(nil), "echelon.vrf.v1.QueryGetUservalResponse")
	proto.RegisterType((*QueryAllUservalRequest)(nil), "echelon.vrf.v1.QueryAllUservalRequest")
	proto.RegisterType((*QueryAllUservalResponse)(nil), "echelon.vrf.v1.QueryAllUservalResponse")
	proto.RegisterType((*QueryVerifyValuesRequest)(nil), "echelon.vrf.v1.QueryVerifyValuesRequest")
	proto.RegisterType((*QueryVerifyValuesResponse)(nil), "echelon.vrf.v1.QueryVerifyValuesResponse")
}

func init() { proto.RegisterFile("echelon/vrf/v1/query.proto", fileDescriptor_c81a177218a0f596) }

var fileDescriptor_c81a177218a0f596 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0xa6, 0x3f, 0xc8, 0x51, 0x21, 0x74, 0xaa, 0x52, 0xd7, 0x44, 0xa6, 0x58, 0x28,
	0x2d, 0x0c, 0x3e, 0xd2, 0x0e, 0x9d, 0x18, 0xda, 0x81, 0x4e, 0x48, 0x60, 0x89, 0x0e, 0x9d, 0xb0,
	0x9b, 0x8b, 0x6b, 0xe1, 0xf8, 0x5c, 0x9f, 0x6d, 0x35, 0xaa, 0x90, 0x10, 0x48, 0x88, 0x11, 0x89,
	0x91, 0x09, 0xf1, 0xcf, 0x74, 0xac, 0xc4, 0xc2, 0x84, 0x50, 0xc2, 0x1f, 0x82, 0x7c, 0x7e, 0x76,
	0xe2, 0xc4, 0xa6, 0x41, 0xea, 0xe6, 0xbb, 0x7b, 0xef, 0xde, 0xe7, 0x7d, 0xdf, 0xf7, 0x12, 0xa4,
	0xd0, 0x93, 0x53, 0xea, 0x32, 0x8f, 0xc4, 0x41, 0x8f, 0xc4, 0x1d, 0x72, 0x16, 0xd1, 0x60, 0xa0,
	0xfb, 0x01, 0x0b, 0x19, 0xbe, 0x03, 0x67, 0x7a, 0x1c, 0xf4, 0xf4, 0xb8, 0xa3, 0xb4, 0x6c, 0xc6,
	0x6c, 0x97, 0x12, 0xd3, 0x77, 0x88, 0xe9, 0x79, 0x2c, 0x34, 0x43, 0x87, 0x79, 0x3c, 0x8d, 0x56,
	0x1e, 0x9f, 0x30, 0xde, 0x67, 0x9c, 0x58, 0x26, 0xa7, 0xe9, 0x35, 0x24, 0xee, 0x58, 0x34, 0x34,
	0x3b, 0xc4, 0x37, 0x6d, 0xc7, 0x13, 0xc1, 0x10, 0xab, 0x4e, 0x55, 0x0d, 0x4c, 0xaf, 0xcb, 0xfa,
	0xb1, 0xe9, 0xc2, 0x79, 0x6b, 0xea, 0x3c, 0xe2, 0x34, 0x18, 0x9f, 0xae, 0xd9, 0xcc, 0x66, 0xe2,
	0x93, 0x24, 0x5f, 0xe9, 0xae, 0xf6, 0x04, 0xc9, 0x2f, 0x93, 0xaa, 0x87, 0x34, 0x34, 0xb2, 0xeb,
	0x0c, 0x7a, 0x16, 0x51, 0x1e, 0xe2, 0x35, 0xb4, 0xe4, 0x78, 0x5d, 0x7a, 0x2e, 0x4b, 0x9b, 0xd2,
	0x76, 0xc3, 0x48, 0x17, 0xda, 0x31, 0xda, 0x28, 0xc9, 0xe0, 0x3e, 0xf3, 0x38, 0xc5, 0x4f, 0x51,
	0x23, 0xa7, 0x12, 0x69, 0xb7, 0x77, 0x36, 0xf4, 0xa2, 0x20, 0x7a, 0x9e, 0x75, 0xb0, 0x78, 0xf9,
	0xeb, 0x7e, 0xcd, 0x18, 0x67, 0x68, 0x16, 0xd0, 0xec, 0xbb, 0xee, 0x0c, 0xcd, 0x33, 0x84, 0xc6,
	0x8a, 0xc0, 0xdd, 0x6d, 0x3d, 0x95, 0x4f, 0x4f, 0xe4, 0xd3, 0xd3, 0x29, 0x80, 0x7c, 0xfa, 0x0b,
	0xd3, 0xa6, 0x90, 0x6b, 0x4c, 0x64, 0x6a, 0xdf, 0x25, 0x68, 0xa0, 0x58, 0xa4, 0xbc, 0x81, 0xfa,
	0xff, 0x35, 0x80, 0x0f, 0x0b, 0x90, 0x0b, 0x02, 0x72, 0xeb, 0x5a, 0xc8, 0xb4, 0x76, 0x81, 0x52,
	0x47, 0xcd, 0x4c, 0xe5, 0x57, 0xe9, 0x18, 0xff, 0x3d, 0x15, 0x03, 0xad, 0xcf, 0xc4, 0x43, 0x4b,
	0x7b, 0x68, 0x05, 0x9c, 0x00, 0xaa, 0xad, 0x4f, 0x37, 0x04, 0x19, 0xd0, 0x4e, 0x16, 0xad, 0xbd,
	0x06, 0x86, 0x7d, 0xd7, 0x9d, 0x62, 0xb8, 0xa9, 0x59, 0x7c, 0x95, 0x00, 0x7b, 0xb2, 0x44, 0x19,
	0x76, 0x7d, 0x7e, 0xec, 0x9b, 0x9b, 0x41, 0x08, 0x6e, 0x3c, 0xa2, 0x81, 0xd3, 0x1b, 0x1c, 0x99,
	0x6e, 0x44, 0x79, 0xa6, 0x40, 0x13, 0x2d, 0xfb, 0x91, 0xf5, 0x86, 0x0e, 0x60, 0x0c, 0xb0, 0xc2,
	0x32, 0x5a, 0xe9, 0x53, 0xce, 0x4d, 0x9b, 0x8a, 0xca, 0x0d, 0x23, 0x5b, 0xe2, 0xbb, 0xa8, 0x1e,
	0x07, 0xb1, 0x5c, 0x17, 0xbb, 0xc9, 0x67, 0x32, 0x49, 0x3f, 0x60, 0xac, 0x27, 0x2f, 0xa6, 0x93,
	0x14, 0x0b, 0x6d, 0x0f, 0xec, 0x59, 0xac, 0x0a, 0xa2, 0x28, 0xe8, 0x56, 0x9c, 0xec, 0x3b, 0xb4,
	0x0b, 0x85, 0xf3, 0xf5, 0xce, 0xb7, 0x25, 0xb4, 0x24, 0x32, 0xf1, 0x27, 0x09, 0x35, 0x72, 0x93,
	0xe2, 0xed, 0x69, 0xdd, 0xaa, 0x1e, 0xbc, 0xf2, 0x68, 0x8e, 0xc8, 0x14, 0x44, 0x6b, 0xbf, 0xff,
	0xf1, 0xe7, 0xcb, 0xc2, 0x26, 0x56, 0xc9, 0xe4, 0x8f, 0x4e, 0xfe, 0x10, 0xc8, 0x85, 0xb0, 0xe5,
	0x5b, 0xfc, 0x41, 0x42, 0xab, 0x79, 0xf6, 0xbe, 0x5b, 0x45, 0x53, 0xf2, 0xe0, 0x2b, 0x68, 0xca,
	0x5e, 0xad, 0xa6, 0x0a, 0x1a, 0x19, 0x37, 0xcb, 0x69, 0xf0, 0x3b, 0x09, 0xad, 0x80, 0x5b, 0x70,
	0xbb, 0xaa, 0xc9, 0xa2, 0xc7, 0x95, 0xad, 0x6b, 0xe3, 0xa0, 0xf8, 0x43, 0x51, 0x5c, 0xc5, 0xad,
	0x42, 0x71, 0x70, 0x63, 0x2e, 0xc4, 0x05, 0x42, 0x90, 0x98, 0xa8, 0xd0, 0xae, 0xea, 0x6d, 0x2e,
	0x88, 0xd9, 0xd7, 0xa2, 0xb5, 0x04, 0x44, 0x13, 0xaf, 0x95, 0x41, 0xe0, 0x8f, 0x12, 0x5a, 0x9d,
	0xf4, 0x53, 0xc5, 0x14, 0x4a, 0x8c, 0x5e, 0x31, 0x85, 0x32, 0x73, 0x6a, 0x0f, 0x04, 0xc3, 0x3d,
	0xbc, 0x51, 0x60, 0x88, 0x27, 0x42, 0x0f, 0x9e, 0x5f, 0x0e, 0x55, 0xe9, 0x6a, 0xa8, 0x4a, 0xbf,
	0x87, 0xaa, 0xf4, 0x79, 0xa4, 0xd6, 0xae, 0x46, 0x6a, 0xed, 0xe7, 0x48, 0xad, 0x1d, 0xef, 0xda,
	0x4e, 0x78, 0x1a, 0x59, 0xfa, 0x09, 0xeb, 0x67, 0xe9, 0x3d, 0x16, 0x79, 0x5d, 0xf1, 0x14, 0xc7,
	0x17, 0xee, 0x92, 0x73, 0x71, 0x6b, 0x38, 0xf0, 0x29, 0xb7, 0x96, 0xc5, 0x9f, 0xd8, 0xee, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xd9, 0x16, 0x21, 0x90, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a randomval by index.
	Randomval(ctx context.Context, in *QueryGetRandomvalRequest, opts ...grpc.CallOption) (*QueryGetRandomvalResponse, error)
	// Queries a list of randomval items.
	RandomvalAll(ctx context.Context, in *QueryAllRandomvalRequest, opts ...grpc.CallOption) (*QueryAllRandomvalResponse, error)
	// Queries a userval by index.
	Userval(ctx context.Context, in *QueryGetUservalRequest, opts ...grpc.CallOption) (*QueryGetUservalResponse, error)
	// Queries a list of userval items.
	UservalAll(ctx context.Context, in *QueryAllUservalRequest, opts ...grpc.CallOption) (*QueryAllUservalResponse, error)
	// Queries a list of verifyValues items.
	VerifyValues(ctx context.Context, in *QueryVerifyValuesRequest, opts ...grpc.CallOption) (*QueryVerifyValuesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Randomval(ctx context.Context, in *QueryGetRandomvalRequest, opts ...grpc.CallOption) (*QueryGetRandomvalResponse, error) {
	out := new(QueryGetRandomvalResponse)
	err := c.cc.Invoke(ctx, "/echelon.vrf.v1.Query/Randomval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RandomvalAll(ctx context.Context, in *QueryAllRandomvalRequest, opts ...grpc.CallOption) (*QueryAllRandomvalResponse, error) {
	out := new(QueryAllRandomvalResponse)
	err := c.cc.Invoke(ctx, "/echelon.vrf.v1.Query/RandomvalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Userval(ctx context.Context, in *QueryGetUservalRequest, opts ...grpc.CallOption) (*QueryGetUservalResponse, error) {
	out := new(QueryGetUservalResponse)
	err := c.cc.Invoke(ctx, "/echelon.vrf.v1.Query/Userval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UservalAll(ctx context.Context, in *QueryAllUservalRequest, opts ...grpc.CallOption) (*QueryAllUservalResponse, error) {
	out := new(QueryAllUservalResponse)
	err := c.cc.Invoke(ctx, "/echelon.vrf.v1.Query/UservalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyValues(ctx context.Context, in *QueryVerifyValuesRequest, opts ...grpc.CallOption) (*QueryVerifyValuesResponse, error) {
	out := new(QueryVerifyValuesResponse)
	err := c.cc.Invoke(ctx, "/echelon.vrf.v1.Query/VerifyValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a randomval by index.
	Randomval(context.Context, *QueryGetRandomvalRequest) (*QueryGetRandomvalResponse, error)
	// Queries a list of randomval items.
	RandomvalAll(context.Context, *QueryAllRandomvalRequest) (*QueryAllRandomvalResponse, error)
	// Queries a userval by index.
	Userval(context.Context, *QueryGetUservalRequest) (*QueryGetUservalResponse, error)
	// Queries a list of userval items.
	UservalAll(context.Context, *QueryAllUservalRequest) (*QueryAllUservalResponse, error)
	// Queries a list of verifyValues items.
	VerifyValues(context.Context, *QueryVerifyValuesRequest) (*QueryVerifyValuesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Randomval(ctx context.Context, req *QueryGetRandomvalRequest) (*QueryGetRandomvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Randomval not implemented")
}
func (*UnimplementedQueryServer) RandomvalAll(ctx context.Context, req *QueryAllRandomvalRequest) (*QueryAllRandomvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomvalAll not implemented")
}
func (*UnimplementedQueryServer) Userval(ctx context.Context, req *QueryGetUservalRequest) (*QueryGetUservalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Userval not implemented")
}
func (*UnimplementedQueryServer) UservalAll(ctx context.Context, req *QueryAllUservalRequest) (*QueryAllUservalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UservalAll not implemented")
}
func (*UnimplementedQueryServer) VerifyValues(ctx context.Context, req *QueryVerifyValuesRequest) (*QueryVerifyValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyValues not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Randomval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRandomvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Randomval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echelon.vrf.v1.Query/Randomval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Randomval(ctx, req.(*QueryGetRandomvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RandomvalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRandomvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomvalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echelon.vrf.v1.Query/RandomvalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomvalAll(ctx, req.(*QueryAllRandomvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Userval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUservalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Userval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echelon.vrf.v1.Query/Userval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Userval(ctx, req.(*QueryGetUservalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UservalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUservalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UservalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echelon.vrf.v1.Query/UservalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UservalAll(ctx, req.(*QueryAllUservalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echelon.vrf.v1.Query/VerifyValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyValues(ctx, req.(*QueryVerifyValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echelon.vrf.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Randomval",
			Handler:    _Query_Randomval_Handler,
		},
		{
			MethodName: "RandomvalAll",
			Handler:    _Query_RandomvalAll_Handler,
		},
		{
			MethodName: "Userval",
			Handler:    _Query_Userval_Handler,
		},
		{
			MethodName: "UservalAll",
			Handler:    _Query_UservalAll_Handler,
		},
		{
			MethodName: "VerifyValues",
			Handler:    _Query_VerifyValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echelon/vrf/v1/query.proto",
}

func (m *QueryGetRandomvalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRandomvalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRandomvalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRandomvalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRandomvalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRandomvalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Randomval.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRandomvalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRandomvalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRandomvalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRandomvalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRandomvalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRandomvalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Randomval) > 0 {
		for iNdEx := len(m.Randomval) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Randomval[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUservalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUservalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUservalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUservalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUservalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUservalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Userval.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllUservalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUservalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUservalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllUservalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUservalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUservalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Userval) > 0 {
		for iNdEx := len(m.Userval) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Userval[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyValuesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyValuesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyValuesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Vrv) > 0 {
		i -= len(m.Vrv)
		copy(dAtA[i:], m.Vrv)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Vrv)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyValuesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyValuesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyValuesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Verified) > 0 {
		i -= len(m.Verified)
		copy(dAtA[i:], m.Verified)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Verified)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetRandomvalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRandomvalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Randomval.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRandomvalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRandomvalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Randomval) > 0 {
		for _, e := range m.Randomval {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUservalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUservalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Userval.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllUservalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllUservalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Userval) > 0 {
		for _, e := range m.Userval {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyValuesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Vrv)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyValuesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Verified)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetRandomvalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRandomvalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRandomvalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRandomvalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRandomvalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRandomvalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Randomval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRandomvalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRandomvalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRandomvalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRandomvalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRandomvalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRandomvalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Randomval = append(m.Randomval, Randomval{})
			if err := m.Randomval[len(m.Randomval)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUservalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUservalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUservalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUservalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUservalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUservalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Userval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUservalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUservalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUservalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUservalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUservalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUservalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userval = append(m.Userval, Userval{})
			if err := m.Userval[len(m.Userval)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyValuesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyValuesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyValuesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vrv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vrv = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyValuesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyValuesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyValuesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Verified = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
